import type { FORMAT } from '../types';

export const SUPPORTED_FORMATS: FORMAT[] = [
   'A',
   'R',
   'N',
   'D',
   'C',
   'E',
   'Q',
   'G',
   'H',
   'I',
   'L',
   'K',
   'M',
   'F',
   'P',
   'S',
   'T',
   'W',
   'Y',
   'V',
   '-',
];

export const COLOR_SHEME: Record<(typeof SUPPORTED_FORMATS)[number], string> = {
   C: '#FFEA00',
   A: '#67E4A6',
   I: '#67E4A6',
   L: '#67E4A6',
   M: '#67E4A6',
   F: '#67E4A6',
   W: '#67E4A6',
   Y: '#67E4A6',
   V: '#67E4A6',
   P: '#67E4A6',
   G: '#C4C4C4',
   D: '#FC9CAC',
   E: '#FC9CAC',
   K: '#BB99FF',
   R: '#BB99FF',
   S: '#80BFFF',
   T: '#80BFFF',
   H: '#80BFFF',
   Q: '#80BFFF',
   N: '#80BFFF',
   '-': '#000000',
};

export const LETTER_WIDTH = 40;
